source 'https://rubygems.org'

#ruby=2.0.0-p645
#ruby-gemset=puppet-puppetserver

gem 'puppet', '3.8.5'
gem 'rake'
gem 'rspec', '< 3.2'
gem 'rspec-puppet'
gem 'puppetlabs_spec_helper'
gem 'rspec_junit_formatter'
gem 'metadata-json-lint'
gem 'puppet-lint'
gem 'puppet-lint-unquoted_string-check'
gem 'puppet-lint-empty_string-check'
gem 'puppet-lint-spaceship_operator_without_tag-check'
gem 'puppet-lint-variable_contains_upcase'
gem 'puppet-lint-absolute_classname-check'
gem 'puppet-lint-undef_in_function-check'
gem 'puppet-lint-leading_zero-check'
gem 'puppet-lint-trailing_comma-check'
gem 'puppet-lint-file_ensure-check'
gem 'puppet-lint-version_comparison-check'
gem 'puppet-lint-fileserver-check'
gem 'puppet-lint-file_source_rights-check'
gem 'puppet-lint-alias-check'
gem 'rspec-puppet-facts'
gem 'ruby-augeas'
gem 'puppet-blacksmith'
